# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:          /:title/
markdown:           kramdown
# relative_permalinks: true

# Setup
title:               SYSU Thesis Blog
tagline:             'Wasif Islam'
description:         'JIE SYSU-CMU'
url:                 'http://washifu.github.io'
baseurl:             'http://washifu.github.io'
paginate:            5

# About/contact
author:              
  name:              Wasif Islam
  url:               'https://www.linkedin.com/in/islamwasif/'
  email:             wislam@andrew.cmu.edu

# Custom vars
version:             1.0.0

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: washifu
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: MD Luffy

 
